# TEST 1
# single_linked_list = SingleLinkedList.new()
# single_linked_list.append_from_iterable(iterable=[1, 2, 3, 4, 1, 6, 7, 1])
# single_linked_list.show()
# new_list = partition(linked_list=single_linked_list, partition_data=6)
# new_list.show()
# new_list = partition(linked_list=single_linked_list, partition_data=4)
# new_list.show()
# new_list = partition(linked_list=single_linked_list, partition_data=2)
# new_list.show()
# new_list = partition(linked_list=single_linked_list, partition_data=7)
# new_list.show()
# new_list = partition(linked_list=single_linked_list, partition_data=5)
# new_list.show()